name: test pipeline manuel

on:
  repository_dispatch:
     types: [incident_report]
         

jobs:
  test-manual:
    runs-on: ubuntu-latest 

    steps:
      - name: Lancement du script
        run: echo "deploiement de l'application"