name: test pipeline manuel

on:
  workflow_dispatch: # Déclenchement manuel activé !

jobs:
  test-manual:
    runs-on: ubuntu-latest # Correction : avec le 't' à la fin

    steps:
      - name: Lancement du script
        run: echo "deploiement de l'application ....." # Syntaxe propre avec espace