name: gemini gmail

on:
  workflow_dispatch:

jobs:
    job-1:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: test 
              uses: actions/setup-python@v6
            
            - run: python test.py
   